# Node.js Task Management Board CI/CD Pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd backend
    npm install
  displayName: 'Install backend dependencies'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Install frontend dependencies and build'

- script: |
    echo "Skipping tests for now - no tests configured"
  displayName: 'Skip tests (no tests available)'

- task: CopyFiles@2
  inputs:
    contents: |
      backend/**
      frontend/dist/**
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files for deployment'

- script: |
    echo "Build completed successfully!"
    echo "Backend built: ✅"
    echo "Frontend built: ✅"
    echo "Ready for deployment to AWS EC2"
  displayName: 'Build Summary'